### PR TITLE
Add CaseCountable

### PR DESCRIPTION
**Pull request by hiltonc**

### CODE REVIEW

**Comment by hiltonc** [comment]
Sorry, rebased due to merge conflict.

**Comment by stephanheilner** [comment]
Does it make it so we don't need to add a case for `Count` when we back a UITableView with an enum? Because it sure looks like it!

**Comment by stephanheilner** [comment]
👍

**Comment by hiltonc** [comment]
I've been using this to avoid needing a `case Count` in my enums. You can just do `MyEnum.count`. But it does assume your enum starts at 0 and doesn't skip any numbers. I don't know of a performant way to avoid those assumptions.

**Comment by stephanheilner** [comment]
Thats fine though, because we have to make that assumption with an enum that will represent a NSIndexPath. This is awesome!

**Pull request merged**
